import logging
from urllib.parse import urlparse

logger = logging.getLogger(__name__)

class EgressNetworkInterceptor:
    """
    Zero-Trust Architecture for Outbound Data.
    Intercepts all outgoing webhook requests generated by autonomous agents.
    Drops payloads destined for unapproved external IP addresses or domains 
    to mathematically prevent prompt-injection data exfiltration.
    """
    WHITELISTED_DOMAINS = {"api.hubapi.com", "your-salesforce-instance.com"}

    @classmethod
    def authorize_outbound_transmission(cls, destination_url: str) -> bool:
        domain = urlparse(destination_url).netloc

        if domain not in cls.WHITELISTED_DOMAINS:
            logger.critical(f"ZERO-TRUST VIOLATION: Attempted data exfiltration to unauthorized domain: {domain}")
            return False

        logger.debug(f"Egress authorized for trusted domain: {domain}")
        return True
