name: AI Pull Request Reviewer

on:
  workflow_dispatch: # <-- Ini membuat skrip HANYA berjalan jika dipicu manual

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        
      - name: Run LLM Code Review
        uses: coderabbitai/openai-pr-reviewer@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.GROQ_API_KEY }}
        with:
          debug: false
          review_simple_changes: false
          review_comment_lgtm: false
