class ROICalculator:
    """
    Tracks the business value generated by automation pipelines.
    Used for client reporting and retainer justification.
    """
    def __init__(self, manual_hourly_rate: float = 25.0):
        self.manual_hourly_rate = manual_hourly_rate
        self.tasks_automated = 0
        self.avg_manual_time_minutes = 15.0 # e.g., manual data extraction

    def log_automated_task(self, count: int = 1):
        self.tasks_automated += count

    def get_client_report(self) -> dict:
        hours_saved = (self.tasks_automated * self.avg_manual_time_minutes) / 60
        money_saved = hours_saved * self.manual_hourly_rate

        return {
            "total_tasks_automated": self.tasks_automated,
            "hours_saved": round(hours_saved, 2),
            "estimated_cost_savings_usd": round(money_saved, 2)
        }
